server.port=8080

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/portfoliodb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1cNv8ofc0HUb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Mail Configuration (Outlook/Hotmail)
spring.mail.host=smtp-mail.outlook.com
spring.mail.port=587
spring.mail.username=victornex2006@hotmail.com
spring.mail.password=wrnnolgpllzocvws
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
